name: App Release
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - 'main'

jobs:
  release:
    if: (github.event.pull_request.merged == true) && (contains(github.head_ref, 'dependabot/github_actions/') == false) && (contains(github.head_ref, 'skip-release/') == false) || (github.event_name == 'workflow_dispatch')
    name: Github Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: checkout
      with:
        fetch-depth: 0

    - name: Bump version and push tag
      id: auto_tag_generation
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: main
        pre_release_branches: stage
        default_prerelease_bump: false
        tag_prefix: ""

    - name: Generate Changelog
      id: auto_changelog_generation
      uses: heinrichreimer/github-changelog-generator-action@v2.4
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        sinceTag: ${{ steps.auto_tag_generation.outputs.previous_tag }}
        unreleased: false
        pullRequests: true
        release_branch: stage
        issues: true


    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        prerelease: false
        tag: ${{ steps.auto_tag_generation.outputs.new_tag }}
        name: ${{ steps.auto_tag_generation.outputs.new_tag }}
        body: ${{ steps.auto_changelog_generation.outputs.changelog }}
